## ============================================================
##  synth.tcl  -  Vivado Non-Project Batch Flow
##  Project : Single-Cycle RV32IM SoC
##  Device  : xc7a35tcsg324-1  (Arty A7-35T)
##  Step    : 19 — Synthesis + Place & Route
##
##  Usage:
##    vivado -mode batch -source synth.tcl
##    vivado -mode batch -source synth.tcl -tclargs <imem_hex>
##
##  The optional argument is the path to your IMEM .hex file.
##  If omitted the IMEM is synthesised empty (all NOPs).
##
##  Outputs (written to ./output/):
##    *.bit           — bitstream for programming
##    utilisation.rpt — LUT/FF/BRAM usage
##    timing.rpt      — worst-case slack (must be ≥ 0)
##    power.rpt       — estimated power
## ============================================================

## ── Configuration ─────────────────────────────────────────────
set PART      "xc7a35tcsg324-1"
set TOP       "soc_top"
set OUTDIR    "./output"

## Optional IMEM hex file (passed on command line or set here)
set IMEM_FILE ""
if { $argc > 0 } { set IMEM_FILE [lindex $argv 0] }

## ── Source Files ──────────────────────────────────────────────
## List every .sv file needed for synthesis.
## Keep in dependency order (leaves first, top last).
set SRC_FILES {
    alu.sv
    regfile.sv
    imm_gen.sv
    branch_unit.sv
    mul_div.sv
    control.sv
    writeback.sv
    pc_logic.sv
    dmem.sv
    csr_regs.sv
    riscv_core.sv
    uart.sv
    gpio.sv
    timer.sv
    bus_fabric.sv
    soc_top.sv
}

## imem.sv is read separately below (may be patched with IMEM_FILE path)

## ── Setup ─────────────────────────────────────────────────────
file mkdir $OUTDIR

## ── Read Sources ──────────────────────────────────────────────
foreach f $SRC_FILES {
    puts "Reading: $f"
    read_verilog -sv $f
}
read_xdc arty_a7.xdc

## ── IMEM Source Selection ─────────────────────────────────────
## If IMEM_FILE is provided, expect imem_init.sv to already exist
## (generated by generate_imem.py). Otherwise use stock imem.sv.
##
## Workflow:
##   python3 firmware/generate_imem.py firmware/hello.hex imem_init.sv
##   vivado -mode batch -source synth.tcl
##
## The -tclargs path is no longer needed — just run generate_imem.py first.

if { [file exists "imem_init.sv"] } {
    puts "Using pre-generated imem_init.sv (firmware baked in)"
    read_verilog -sv imem_init.sv
} else {
    puts "imem_init.sv not found — using stock imem.sv (NOP-filled)"
    read_verilog -sv imem.sv
}

## ── Synthesis ─────────────────────────────────────────────────
puts "\n=== Synthesis ==="
synth_design \
    -top    $TOP \
    -part   $PART \
    -flatten_hierarchy rebuilt \
    -fsm_extraction     one_hot \
    -keep_equivalent_registers \
    -resource_sharing   off \
    -no_lc

write_checkpoint -force $OUTDIR/post_synth.dcp
report_utilization -file $OUTDIR/utilisation_synth.rpt
report_timing_summary -file $OUTDIR/timing_synth.rpt -max_paths 10

## ── Optimise ──────────────────────────────────────────────────
puts "\n=== Optimise ==="
opt_design

## ── Place ─────────────────────────────────────────────────────
puts "\n=== Place ==="
place_design
phys_opt_design

write_checkpoint -force $OUTDIR/post_place.dcp
report_utilization    -file $OUTDIR/utilisation_place.rpt
report_timing_summary -file $OUTDIR/timing_place.rpt -max_paths 10

## ── Route ─────────────────────────────────────────────────────
puts "\n=== Route ==="
route_design
phys_opt_design

write_checkpoint -force $OUTDIR/post_route.dcp

## ── Final Reports ─────────────────────────────────────────────
puts "\n=== Reports ==="
report_utilization    -file $OUTDIR/utilisation.rpt    -hierarchical
report_timing_summary -file $OUTDIR/timing.rpt         -max_paths 50
report_power          -file $OUTDIR/power.rpt
report_drc            -file $OUTDIR/drc.rpt

## ── Timing Check ──────────────────────────────────────────────
set timing_paths [get_timing_paths -max_paths 1 -nworst 1 -quiet]
if { $timing_paths ne "" } {
    set wns [get_property SLACK $timing_paths]
    puts "\n=== Worst Negative Slack: $wns ns ==="
    if { [expr {$wns < 0}] } {
        puts "WARNING: Timing NOT met — tighten critical path or reduce clock."
    } else {
        puts "Timing CLOSED at 100 MHz."
    }
} else {
    puts "\n=== Timing: no paths found — check timing.rpt manually ==="
}

## ── Bitstream ─────────────────────────────────────────────────
puts "\n=== Bitstream ==="
write_bitstream -force $OUTDIR/${TOP}.bit

## ── Program (optional — uncomment if board is connected) ───────
# open_hw_manager
# connect_hw_server
# open_hw_target
# set_property PROGRAM.FILE $OUTDIR/${TOP}.bit [current_hw_device]
# program_hw_devices [current_hw_device]
# close_hw_target
# close_hw_manager

puts "\n=== Done. Bitstream: $OUTDIR/${TOP}.bit ==="
